import { createContext, useContext, useState, useEffect } from 'react';

const LanguageContext = createContext();

const translations = {
    en: {
        dashboard: 'Dashboard',
        all_tasks: 'All Tasks',
        manage_tasks: 'Manage Tasks',
        machines: 'Machines',
        users: 'Users',
        analytics: 'Analytics',
        my_tasks: 'My Tasks',
        live_connected: 'Live Connected',
        disconnected: 'Disconnected',
        sign_out: 'Sign Out',
        welcome: 'Welcome back',
        active: 'Active',
        pending: 'Pending',
        done: 'Done',
        task_pool: 'Available Task Pool',
        active_tasks: 'Your Active Tasks',
        pending_paused: 'Pending / Paused',
        completion_logs: 'Your Completion Logs',
        view_history: 'View History',
        accept_task: 'Accept Task',
        shopfloor_tasks: 'Shopfloor Tasks',
        work_order: 'Work Order',
        search: 'Search...',
        all_statuses: 'All Statuses',
        all_priorities: 'All Priorities',
        new_task: 'New Task',
        mark_complete: 'Mark Complete',
        pause_task: 'Pause Task',
        resume_task: 'Resume Task',
        task: 'Task',
        worker: 'Worker',
        machine: 'Machine',
        priority: 'Priority',
        status: 'Status',
        expected: 'Expected',
        claimed_by: 'Claimed by',
        unassigned: 'Unassigned',
        not_started: 'Not Started',
        in_progress: 'In Progress',
        paused: 'Paused',
        completed: 'Completed',
        delayed: 'Delayed',
        high: 'High',
        medium: 'Medium',
        low: 'Low',
        task_title: 'Task Title',
        description: 'Description',
        assign_machine: 'Assign Machine',
        expected_time: 'Expected Time (min)',
        delete_task: 'Delete Task?',
        cancel: 'Cancel',
        confirm_delete: 'Are you sure you want to delete',
        task_is_claimed: 'Task is Claimed',
        will_vanish: 'It will vanish from their dashboard.',
        override_status: 'Override Status',
        force_status: 'Force Status',
        override: 'Override',
        take_break: 'Take Break',
        end_break: 'End Break',
        on_break: 'On Break',
        break_taken: 'Break Taken',
        break_limit_reached: 'Daily break limit reached',
        requests: 'Requests',
    },
    hi: {
        dashboard: 'डैशबोर्ड',
        all_tasks: 'सभी कार्य',
        manage_tasks: 'कार्यों का प्रबंधन',
        machines: 'मशीनें',
        users: 'उपयोगकर्ता',
        analytics: 'विश्लेषण',
        my_tasks: 'मेरे कार्य',
        live_connected: 'लाइव जुड़ा हुआ',
        disconnected: 'डिस्कनेक्ट हो गया',
        sign_out: 'साइन आउट',
        welcome: 'वापस स्वागत है',
        active: 'सक्रिय',
        pending: 'लंबित',
        done: 'पूर्ण',
        task_pool: 'उपलब्ध टास्क पूल',
        active_tasks: 'आपके सक्रिय कार्य',
        pending_paused: 'लंबित / रुका हुआ',
        completion_logs: 'आपकी पूर्णता लॉग',
        view_history: 'इतिहास देखें',
        accept_task: 'कार्य स्वीकार करें',
        shopfloor_tasks: 'शॉपफ्लोर टास्क',
        work_order: 'वर्क ऑर्डर',
        search: 'खोजें...',
        all_statuses: 'सभी स्थितियाँ',
        all_priorities: 'सभी प्राथमिकताएं',
        new_task: 'नया कार्य',
        mark_complete: 'पूर्ण चिह्नित करें',
        pause_task: 'कार्य रोकें',
        resume_task: 'कार्य फिर से शुरू करें',
        task: 'कार्य',
        worker: 'कर्मचारी',
        machine: 'मशीन',
        priority: 'प्राथमिकता',
        status: 'स्थिति',
        expected: 'अपेक्षित',
        claimed_by: 'द्वारा दावा किया गया',
        unassigned: 'अनअसाइन किया गया',
        not_started: 'शुरू नहीं हुआ',
        in_progress: 'प्रगति पर',
        paused: 'रुका हुआ',
        completed: 'पूर्ण',
        delayed: 'विलंबित',
        high: 'उच्च',
        medium: 'मध्यम',
        low: 'निम्न',
        task_title: 'कार्य का शीर्षक',
        description: 'विवरण',
        assign_machine: 'मशीन असाइन करें',
        expected_time: 'अपेक्षित समय (मिनट)',
        delete_task: 'कार्य हटाएं?',
        cancel: 'रद्द करें',
        confirm_delete: 'क्या आप वाकई हटाना चाहते हैं',
        task_is_claimed: 'कार्य का दावा किया गया है',
        will_vanish: 'यह उनके डैशबोर्ड से हट जाएगा।',
        override_status: 'स्थिति बदलें',
        force_status: 'बलपूर्वक स्थिति चुनें',
        override: 'बदलें',
        take_break: 'ब्रेक लें',
        end_break: 'ब्रेक खत्म करें',
        on_break: 'ब्रेक पर',
        break_taken: 'ब्रेक लिया गया',
        break_limit_reached: 'दैनिक ब्रेक सीमा समाप्त',
        requests: 'अनुरोध',
        logs: 'लॉग्स',
        monitor: 'मॉनिटर',
    }
};

export function LanguageProvider({ children }) {
    const [lang, setLang] = useState(localStorage.getItem('lang') || 'en');

    useEffect(() => {
        localStorage.setItem('lang', lang);
    }, [lang]);

    const t = (key) => {
        return translations[lang][key] || key;
    };

    return (
        <LanguageContext.Provider value={{ lang, setLang, t }}>
            {children}
        </LanguageContext.Provider>
    );
}

export const useLanguage = () => useContext(LanguageContext);
